### ISSUE TITLE
scan of available devices

### ISSUE THREAD

**Issue by trilu2000** [pfandfrei/Homegear-Xiaomi-Smarthome#4]
Hi, i have added some new devices to the Hub - one cube and a water leak sensor.
Thought i can get them into homegear by running
homegear -e rs DeviceScripts/Xiaomi/MiSmartHome.php

What i get back is:
PHP Fatal error:  Uncaught Error: Call to a member function updateData() on null in /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiGateway.php:230
Stack trace:
#0 /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiCentral.php(155): MiGateway->getDeviceData(Object(Homegear\Homegear))
#1 /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiCentral.php(74): MiCentral->createDevices(Object(Homegear\Homegear), Object(MiGateway))
#2 /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiSmartHome.php(111): MiCentral->discover()
#3 {main}
  thrown in /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiGateway.php on line 230#### MiSmartHome for Homegear 0.7.x ####

**Comment by trilu2000** [comment]
sorry, updated the files and now it had worked
